language: php

cache:
  directories:
  - $HOME/.composer/cache
  - vendor

php:
  - 7.3

install:
  - composer self-update
  - composer install --dev --prefer-dist

before_script:
  - mkdir -p build/logs

script:
  - composer test-travis

after_script:
  - bash <(curl -s https://codecov.io/bash)
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml
